[package]
name = "tacky"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["tacky-build", "tacky-macros", "testing", "pbrs"]


[dependencies]
bytes = "1"


[dev-dependencies]
prost = "0.12"
